config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :databases
  resources :projects
  resources :grants, only: [:new, :create]
end

app/models/project.rb
class Project < Base
  attr_accessor :name, :namespace, :id

  class << self
    def find(id)
      instantiate(api.resource(id))
    end

    def instantiate(app)
      full_name = app.attributes['id'].split(':').last
      database = Project.new(
        id: app.id.id,
        name: full_name.split('/')[-1],
        namespace: full_name.split('/')[0...-1].join('/')
      )
    end

    def all
      api.resources(kind: 'policy', search: 'application').map do |db|
        if db.attributes['annotations'].select { |a| a['name'] == 'resource_type' && a['value'] == 'application' }.present?
          instantiate(db)
        end
      end.compact.sort { |x,y| x.id <=> y.id }
    end
  end

  def resources
    puts "id: #{id}"
    Base.api.role(id).memberships.map{|m| m.id }.select{|m| m.id.include?(':group:')}.map{|m| m.id.scan(/group:(.+)\/secrets-users/).first.last}
  end

  def save
    Base.api.load_policy(namespace, policy(name))
  end

  def update
    raise 'update not implemented'
  end

  def policy(name)
    <<-POLICY
- !policy
  id: #{name}
  annotations:
    resource_type: application
  body:
  - !layer

  - !host-factory
    layer: [ !layer ]
POLICY
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :namespace)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-4">
    <%= bootstrap_form_with(model: project, local: true) do |form| %>
      <% if project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.text_field :name %>
      <%= form.select :namespace, [['development', 'applications/development'],['staging', 'applications/staging'],['integration', 'applications/integration'],['production','applications/production']], {include_blank: true} %>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>
<%= link_to 'Show', project_path(@project.id) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Namespace</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to(project.name, project_path(project.id)) %></td>
        <td><%= project.namespace %></td>
        <td><%= link_to 'Edit', edit_project_path(project.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div class="container-fluid">
  <h1>New Project</h1>
</div>

<div class="container-fluid">
  <%= render 'form', project: @project %>
</div>
<div class="container-fluid">
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tbody>
    <tr>
      <th scope="col">Name</th>
      <td><%= @project.name %></td>
    </tr>
    <tr>
      <th scope="col">Namespace</th>
      <td><%= @project.namespace %></td>
    </tr>
    <tr>
      <th scope="col">Resources</th>
      <td>
        <ul>
          <% @project.resources.each do |resource| %>
            <li><%= resource %></li>
          <% end %>
        </ul>
      </td>
    </tr>
  </tbody>
</table>
<%= link_to 'Enable Database', new_grant_path(project_id: @project.id) %> |
<%= link_to 'Edit', edit_project_path(@project.id) %> |
<%= link_to 'Back', projects_path %>