config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :databases
  resources :projects
  resources :grants, only: [:new, :create]
end

app/models/grant.rb
class Grant < Base

  attr_accessor :project_id, :resource_id

  def save
    scoped_project = project_id.split(':')[-1]
    scoped_resource = resource_id.split(':')[-1]
    # raise "project_id: #{scoped_project}, resource_id: #{scoped_resource}"
    api = Database.api
    puts "namespace: #{scoped_project.split('/')[0...-1].join('/')}"
    puts "policy: #{policy(scoped_project.split('/')[-1], scoped_resource)}"
    #api.load_policy(scoped_project.split('/')[0...-1].join('/'), policy(scoped_project.split('/')[-1], scoped_resource.split('/')[-1]))
    api.load_policy('root', policy(scoped_project, scoped_resource))
  end

  def policy(project_id, resource_id)
    <<-POLICY
- !grant
  member: !layer #{project_id}
  role: !group #{resource_id}/secrets-users
POLICY
  end
end

app/controllers/grants_controller.rb
class GrantsController < ApplicationController
  # before_action :set_grant, only: [:show, :edit, :update, :destroy]

  # GET /grants
  # GET /grants.json
  # def index
  #   @grants = Grant.all
  # end

  # GET /grants/1
  # GET /grants/1.json
  # def show
  # end

  # GET /grants/new
  def new
    # raise params
    @grant = Grant.new(project_id: params[:project_id], resource_id: params[:resource_id])
  end

  # GET /grants/1/edit
  # def edit
  # end

  # POST /grants
  # POST /grants.json
  def create
    @grant = Grant.new(grant_params)

    respond_to do |format|
      if @grant.save
        format.html { redirect_to project_path(@grant.project_id), notice: 'Grant was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /grants/1
  # PATCH/PUT /grants/1.json
  # def update
  #   respond_to do |format|
  #     if @grant.update(grant_params)
  #       format.html { redirect_to @grant, notice: 'Grant was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @grant }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @grant.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /grants/1
  # DELETE /grants/1.json
  # def destroy
  #   @grant.destroy
  #   respond_to do |format|
  #     format.html { redirect_to grants_url, notice: 'Grant was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_grant
    #   @grant = Grant.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grant_params
      params.require(:grant).permit(:project_id, :resource_id)
    end
end

app/helpers/grants_helper.rb
module GrantsHelper
end

app/views/grants/_form.html.erb
<%= bootstrap_form_with(model: grant, local: true) do |form| %>
  <% if grant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grant.errors.count, "error") %> prohibited this grant from being saved:</h2>

      <ul>
      <% grant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.select :project_id, Project.all.map {|p| [p.id.split(':')[-1], p.id] }, { include_blank: true } %>
  <%= form.select :resource_id, Database.all.map {|d| [d.id.split(':')[-1], d.id] }, { include_blank: true } %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grants/edit.html.erb
<h1>Editing Grant</h1>

<%= render 'form', grant: @grant %>

<%= link_to 'Show', @grant %> |
<%= link_to 'Back', grants_path %>

app/views/grants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grants</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Resource</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grants.each do |grant| %>
      <tr>
        <td><%= grant.project %></td>
        <td><%= grant.resource %></td>
        <td><%= link_to 'Show', grant %></td>
        <td><%= link_to 'Edit', edit_grant_path(grant) %></td>
        <td><%= link_to 'Destroy', grant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grant', new_grant_path %>

app/views/grants/new.html.erb
<h1>New Grant</h1>

<%= render 'form', grant: @grant %>

<%= link_to 'Back', grants_path %>

app/views/grants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @grant.project %>
</p>

<p>
  <strong>Resource:</strong>
  <%= @grant.resource %>
</p>

<%= link_to 'Edit', edit_grant_path(@grant) %> |
<%= link_to 'Back', grants_path %>